#ifndef __DCHMILANGUAGE_H__
#define __DCHMILANGUAGE_H__
/*****************************************************************************/
#define DEF_LANG_NUM					2
#define DEF_LANG_CHECK_DISPLAY_SIZE		64
/*****************************************************************************/
#define DEF_LANG_EN						0	
#define	DEF_LANG_CN						1
#define	DEF_LANG_JP						2
/*****************************************************************************/
extern code char LANG_CHECK_DISPLAY_PROCESSOR_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_PROCESSOR_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_EPROM_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_EPROM_Fail[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_SI7060_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_SI7060_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_MCP79412_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_MCP79412_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE]; 
extern code char LANG_CHECK_DISPLAY_BACKUP_FLASH_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_BACKUP_FLASH_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_CH376_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_CH376_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_PN7150B0HN_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_PN7150B0HN_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_NRF24L01_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_NRF24L01_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_TEMPERATURE_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_TEMPERATURE_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
#endif
