#ifndef __DCHMILANGUAGE_H__
#define __DCHMILANGUAGE_H__
/*****************************************************************************/
extern code char *LANG_CHECK_DISPLAY_PROCESSOR_PASS;
extern code char *LANG_CHECK_DISPLAY_PROCESSOR_FAIL;
extern code char *LANG_CHECK_DISPLAY_EPROM_PASS;
extern code char *LANG_CHECK_DISPLAY_EPROM_Fail;
extern code char *LANG_CHECK_DISPLAY_SI7060_PASS;
extern code char *LANG_CHECK_DISPLAY_SI7060_FAIL;
extern code char *LANG_CHECK_DISPLAY_MCP79412_PASS;
extern code char *LANG_CHECK_DISPLAY_MCP79412_FAIL; 
extern code char *LANG_CHECK_DISPLAY_BACKUP_FLASH_PASS;
extern code char *LANG_CHECK_DISPLAY_BACKUP_FLASH_FAIL;
extern code char *LANG_CHECK_DISPLAY_CH376_PASS;
extern code char *LANG_CHECK_DISPLAY_CH376_FAIL;
extern code char *LANG_CHECK_DISPLAY_PN7150B0HN_PASS;
extern code char *LANG_CHECK_DISPLAY_PN7150B0HN_FAIL;
extern code char *LANG_CHECK_DISPLAY_NRF24L01_PASS;
extern code char *LANG_CHECK_DISPLAY_NRF24L01_FAIL;
extern code char *LANG_CHECK_DISPLAY_TEMPERATURE_PASS;
extern code char *LANG_CHECK_DISPLAY_TEMPERATURE_FAIL;
extern code char *LANG_CHECK_DISPLAY_LASER_DRIVER_PASS;
extern code char *LANG_CHECK_DISPLAY_LASER_DRIVER_FAIL;
extern code char *LANG_CHECK_DISPLAY_SAFETY_INTERLOCK_PASS;
extern code char *LANG_CHECK_DISPLAY_SAFETY_INTERLOCK_FAIL;
extern code char *LANG_CHECK_DISPLAY_WIRE_FOOTCONTROL_PASS;
extern code char *LANG_CHECK_DISPLAY_WIRE_FOOTCONTROL_FAIL; 
extern code char *LANG_CHECK_DISPLAY_FIBER_SENSOR_PASS;
extern code char *LANG_CHECK_DISPLAY_FIBER_SENSOR_FAIL;
extern code char *LANG_CHECK_DISPLAY_WIRELESS_FOOTCONTROL_PASS;
extern code char *LANG_CHECK_DISPLAY_WIRELESS_FOOTCONTROL_FAIL; 
extern code char *LANG_CHECK_DISPLAY_PROBATION_PASS;
extern code char *LANG_CHECK_DISPLAY_PROBATION_FAIL;
extern code char *LANG_WARN_MSG_INTERLOCK_UNPLUG;
extern code char *LANG_WARN_MSG_FOOTSWITCH_UNPLUG;
extern code char *LANG_WARN_MSG_ESTOP_PRESS;
extern code char *LANG_WARN_MSG_FIBER_UNPLUG;
extern code char *LANG_WARN_MSG_FIBER_MISSMATE;
extern code char *LANG_WARN_MSG_DIODE0_HTEMP;
extern code char *LANG_WARN_MSG_DIODE1_HTEMP;
extern code char *LANG_WARN_MSG_ENVI_HTEMP;
extern code char *LANG_WARN_MSG_DRIVE_HTEMP;
extern code char *LANG_WARN_MSG_NO_ERROR;
#endif
