#include "dcHmiLanguage.h"
/*****************************************************************************/
code char LANG_CHECK_DISPLAY_PROCESSOR_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:Processor Pass",
	"自检:处理器正常"
};
code char LANG_CHECK_DISPLAY_PROCESSOR_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:Processor Fail!!!",
	"自检:处理器失败"
};
code char LANG_CHECK_DISPLAY_EPROM_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:NVRAM Pass",
	"自检:NVRAM 通过"
};
code char LANG_CHECK_DISPLAY_EPROM_Fail[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:NVRAM Fail",
	"自检:NVRAM 失败"
};
code char LANG_CHECK_DISPLAY_SI7060_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:SI7060 Pass",
	"自检:SI7060 通过"
};
code char LANG_CHECK_DISPLAY_SI7060_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:SI7060 Fail!",
	"自检:SI7060 失败"
};
code char LANG_CHECK_DISPLAY_MCP79412_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:MCP79412 Pass",
	"自检:MCP79412 通过"
};
code char LANG_CHECK_DISPLAY_MCP79412_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:MCP79412 Fail",
	"自检: MCP79412 失败"
};
code char LANG_CHECK_DISPLAY_BACKUP_FLASH_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:Backup Memory Pass",
	"自检:Backup Flash 通过"
};
code char LANG_CHECK_DISPLAY_BACKUP_FLASH_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:Backup Memeory Fail",
	"自检:备份内存 失败"
};
code char LANG_CHECK_DISPLAY_CH376_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:CH376 PASS",
	"自检:CH376 通过"
};
code char LANG_CHECK_DISPLAY_CH376_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:CH376 FAIL",
	"自检:CH376 失败"
};
code char LANG_CHECK_DISPLAY_PN7150B0HN_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:PN7150B0HN PASS",
	"自检:PN7150B0HN  通过"
};
code char LANG_CHECK_DISPLAY_PN7150B0HN_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:PN7150B0HN FAIL",
	"自检:PN7150B0HN 失败"
};
code char LANG_CHECK_DISPLAY_NRF24L01_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:NRF24L01 PASS",
	"自检:NRF24L01  通过"
};
code char LANG_CHECK_DISPLAY_NRF24L01_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:NRF24L01 FAIL",
	"自检:NRF24L01 失败"
};
code char LANG_CHECK_DISPLAY_TEMPERATURE_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:Temperature PASS",
	"自检:温度 通过"
};
code char LANG_CHECK_DISPLAY_TEMPERATURE_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"SELF-CHECK:Temperature PASS",
	"自检:温度 通过"
};
code char LANG_CHECK_DISPLAY_SAFETY_INTERLOCK_FAIL_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"",
	""
};
code char LANG_CHECK_DISPLAY_SAFETY_INTERLOCK_FAIL_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"",
	""
};
code char LANG_CHECK_DISPLAY_WIRE_FOOTCONTROL_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"",
	""
};
code char LANG_CHECK_DISPLAY_WIRE_FOOTCONTROL_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"",
	""
};
code char LANG_CHECK_DISPLAY_FIBER_SENSOR_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"",
	""
};
code char LANG_CHECK_DISPLAY_FIBER_SENSOR_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"",
	""
};
code char LANG_CHECK_DISPLAY_WIRELESS_FOOTCONTROL_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"",
	""
};
code char LANG_CHECK_DISPLAY_WIRELESS_FOOTCONTROL_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"",
	""
};
code char LANG_CHECK_DISPLAY_PROBATION_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"",
	""
};
code char LANG_CHECK_DISPLAY_PROBATION_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE] = {
	"",
	""
};
