#ifndef __DCHMIRES_H__
#define __DCHMIRES_H__
/*****************************************************************************/
#define GDDC_PAGE_PASSCODE_KEY_NUM1					1
#define GDDC_PAGE_PASSCODE_KEY_NUM2					2
#define GDDC_PAGE_PASSCODE_KEY_NUM3					3
#define GDDC_PAGE_PASSCODE_KEY_NUM4					4
#define GDDC_PAGE_PASSCODE_KEY_NUM5					5
#define GDDC_PAGE_PASSCODE_KEY_NUM6					6
#define GDDC_PAGE_PASSCODE_KEY_NUM7					7
#define GDDC_PAGE_PASSCODE_KEY_NUM8					8
#define GDDC_PAGE_PASSCODE_KEY_NUM9					9
#define GDDC_PAGE_PASSCODE_KEY_NUM0					10
#define GDDC_PAGE_PASSCODE_KEY_CANCEL				11
#define GDDC_PAGE_PASSCODE_KEY_BACKSPACE			12
#define GDDC_PAGE_PASSCODE_KEY_CHANGEPASSCODE		13
#define GDDC_PAGE_PASSCODE_KEY_ENTER				14
#define GDDC_PAGE_PASSCODE_TEXTDISPLAY				15
/*****************************************************************************/
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM1				1
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM2				2
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM3				3
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM4				4
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM5				5
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM6				6
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM7				7
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM8				8
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM9				9
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM0				10
#define GDDC_PAGE_NEWPASSCODE_KEY_CANCEL			11
#define GDDC_PAGE_NEWPASSCODE_KEY_BACKSPACE			12
#define GDDC_PAGE_NEWPASSCODE_KEY_SAVE				13
#define GDDC_PAGE_NEWPASSCODE_KEY_BACK				14
#define GDDC_PAGE_NEWPASSCODE_TEXTDISPLAY			15
/*****************************************************************************/
#define GDDC_PAGE_STANDBY_KEY_POWER_CH0_ADD			1						
#define GDDC_PAGE_STANDBY_KEY_POWER_CH0_DEC			2
#define GDDC_PAGE_STANDBY_KEY_POWER_CH1_ADD			3
#define GDDC_PAGE_STANDBY_KEY_POWER_CH1_DEC			4
#define GDDC_PAGE_STANDBY_KEY_POSWIDTH_ADD			5		
#define GDDC_PAGE_STANDBY_KEY_POSWIDTH_DEC			6
#define GDDC_PAGE_STANDBY_KEY_NEGWIDTH_ADD			7
#define GDDC_PAGE_STANDBY_KEY_NEGWIDTH_DEC			8
#define GDDC_PAGE_STANDBY_KEY_GROUP_ADD				9
#define GDDC_PAGE_STANDBY_KEY_GROUP_DEC				10
#define GDDC_PAGE_STANDBY_KEY_SPACE_ADD				11
#define GDDC_PAGE_STANDBY_KEY_SPACE_DEC				12
/*****************************************************************************/
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_POSWIDTH		13
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_NEGWIDTH		14
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_GROUP			15
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_SPACE			16

#define GDDC_PAGE_STANDBY_KEY_READY					17
#define GDDC_PAGE_STANDBY_KEY_STANDBY				18
#define GDDC_PAGE_STANDBY_KEY_MODE_CW				19
#define	GDDC_PAGE_STANDBY_KEY_MODE_MP				20
#define GDDC_PAGE_STANDBY_KEY_MODE_GP				21
#define GDDC_PAGE_STANDBY_KEY_MODE_EVLA_SEGMENT		22
#define GDDC_PAGE_STNADBY_KEY_MODE_EVLA_SIGNAL		23
#define GDCC_PAGE_STANDBY_KEY_MODE_DERMA			24
#define GDDC_PAGE_STANDBY_KEY_OPTION				25
#define GDDC_PAGE_STANDBY_KEY_SCHEME_SAVE			26
#define GDDC_PAGE_STANDBY_KEY_SCHEME_NEXT			27//+
#define GDDC_PAGE_STANDBY_KEY_SCHEME_LAST			28//-
#define GDDC_PAGE_STANDBY_KEY_SELECT_CH0			29
#define GDDC_PAGE_STANDBY_KEY_SELECT_CH1			30
#define GDDC_PAGE_STANDBY_KEY_SELECT_BOTH			31

#define GDDC_PAGE_STANDBY_TEXTDISPLAY_NAME			29
#define GDDC_PAGE_STANDBY_KEY_SCHEME_DEFAULT		30
#endif