#include "dcHmiLanguage.h"
/*****************************************************************************/
code char *LANG_CHECK_DISPLAY_PROCESSOR_PASS = "SELF-CHECK:Processor Pass";
code char *LANG_CHECK_DISPLAY_PROCESSOR_FAIL = "SELF-CHECK:Processor Fail";
code char *LANG_CHECK_DISPLAY_EPROM_PASS = "SELF-CHECK:NVRAM Pass";
code char *LANG_CHECK_DISPLAY_EPROM_FAIL = "SELF-CHECK:NVRAM Fail";
code char *LANG_CHECK_DISPLAY_SI7060_PASS = "SELF-CHECK:SI7060 Pass";
code char *LANG_CHECK_DISPLAY_SI7060_FAIL = "SELF-CHECK:SI7060 Fail";
code char *LANG_CHECK_DISPLAY_MCP79412_PASS = "SELF-CHECK:MCP79412 Pass";
code char *LANG_CHECK_DISPLAY_MCP79412_FAIL = "SELF-CHECK:MCP79412 Fail";
code char *LANG_CHECK_DISPLAY_BACKUP_FLASH_PASS = "SELF-CHECK:Backup Memory Pass";
code char *LANG_CHECK_DISPLAY_BACKUP_FLASH_FAIL = "SELF-CHECK:Backup Memeory Fail";
code char *LANG_CHECK_DISPLAY_CH376_PASS = "SELF-CHECK:CH376 Pass";
code char *LANG_CHECK_DISPLAY_CH376_FAIL = "SELF-CHECK:CH376 Fail";
code char *LANG_CHECK_DISPLAY_PN7150B0HN_PASS = "SELF-CHECK:PN7150B0HN Pass";
code char *LANG_CHECK_DISPLAY_PN7150B0HN_FAIL = "SELF-CHECK:PN7150B0HN Fail";
code char *LANG_CHECK_DISPLAY_NRF24L01_PASS = "SELF-CHECK:NRF24L01 Pass";
code char *LANG_CHECK_DISPLAY_NRF24L01_FAIL = "SELF-CHECK:NRF24L01 Fail";
code char *LANG_CHECK_DISPLAY_TEMPERATURE_PASS = "SELF-CHECK:Temperature Pass";
code char *LANG_CHECK_DISPLAY_TEMPERATURE_FAIL = "SELF-CHECK:Temperature Fail";
code char *LANG_CHECK_DISPLAY_LASER_DRIVER_PASS = "SELF-CHECK:Laser Driver Pass";
code char *LANG_CHECK_DISPLAY_LASER_DRIVER_FAIL = "SELF-CHECK:Laser Driver Fail";
code char *LANG_CHECK_DISPLAY_SAFETY_INTERLOCK_PASS = "SELF-CHECK:Safety Interlock Pass";
code char *LANG_CHECK_DISPLAY_SAFETY_INTERLOCK_FAIL = "SELF-CHECK:Safety Interlock Fail";
code char *LANG_CHECK_DISPLAY_WIRE_FOOTCONTROL_PASS = "SELF-CHECK:Wire Footcontrol Pass";
code char *LANG_CHECK_DISPLAY_WIRE_FOOTCONTROL_FAIL = "SELF-CHECK:Wire Footcontrol Fail";
code char *LANG_CHECK_DISPLAY_FIBER_SENSOR_PASS = "SELF-CHECK:Fiber Sensor Pass";
code char *LANG_CHECK_DISPLAY_FIBER_SENSOR_FAIL = "SELF-CHECK:Fiber Sensor Fail";
code char *LANG_CHECK_DISPLAY_WIRELESS_FOOTCONTROL_PASS = "SELF-CHECK:Wireless footcontrol Pass";
code char *LANG_CHECK_DISPLAY_WIRELESS_FOOTCONTROL_FAIL = "SELF-CHECK:Wireless footcontrol Fail";
code char *LANG_CHECK_DISPLAY_PROBATION_PASS = "SELF-CHECK:Probation Pass";
code char *LANG_CHECK_DISPLAY_PROBATION_FAIL = "SELF-CHECK:Probation Fail";
code char *LANG_WARN_MSG_NO_ERROR = "";
code char *LANG_WARN_MSG_INTERLOCK_UNPLUG = "Door interlock disconnected";//安全连锁没插
code char *LANG_WARN_MSG_FOOTSWITCH_UNPLUG = "Footswitch not connected";//脚踏没插
code char *LANG_WARN_MSG_ESTOP_PRESS = "ESTOP Press";
code char *LANG_WARN_MSG_FIBER_UNPLUG = "No fiber connected ";//光纤没插或者RFID不识别
code char *LANG_WARN_MSG_FIBER_MISSMATE = "Fiber Unmate";
code char *LANG_WARN_MSG_OUT_ENERGY = "Energy out of tolerance";//功率偏差超20%，预留功能，可以以后实现
code char *LANG_WARN_MSG_DIODE0_HTEMP = "Laser overheating";//温度过高
code char *LANG_WARN_MSG_DIODE0_LTEMP = "Laser temperature too low";//温度过低
code char *LANG_WARN_MSG_DIODE0_OVERCURRENT = "Laser current exceeds set value";//电流超过限定值，保护激光器
code char *LANG_WARN_MSG_DIODE1_OVERCURRENT = "Laser current exceeds set value";//电流超过限定值，保护激光器
code char *LANG_WARN_MSG_NTC_ERROR = "Thermistor Error";//热敏电阻故障
code char *LANG_WARN_MSG_DIODE1_HTEMP = "Diode 1 High Temperature";
code char *LANG_WARN_MSG_ENVI_HTEMP = "Envi High Temperature";
code char *LANG_WARN_MSG_DRIVE_HTEMP = "PowerSupply High Temperature";
code char *LANG_WARN_MSG_FOOT_DEPRESSED = "Foot/finger switch is depressed";//脚踏按下去没弹起来
code char *LANG_WARN_MSG_LASER_EMIT = "Laser is firing";//激光正在发射
code char *LANG_WARN_MSG_WAIT_TRIGGER ="Wait Laser Trigger";//等待激光触发


