#ifndef __DCHMILANGUAGE_H__
#define __DCHMILANGUAGE_H__
/*****************************************************************************/
#define DEF_LANG_NUM					2
#define DEF_LANG_CHECK_DISPLAY_SIZE		64
/*****************************************************************************/
#define DEF_LANG_EN						0	
#define	DEF_LANG_CN						1
#define	DEF_LANG_JP						2
/*****************************************************************************/
extern code char LANG_CHECK_DISPLAY_PROCESSOR_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_PROCESSOR_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_EPROM_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_EPROM_Fail[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_SI7060_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_SI7060_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_MCP79412_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_MCP79412_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE]; 
extern code char LANG_CHECK_DISPLAY_BACKUP_FLASH_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_BACKUP_FLASH_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_CH376_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_CH376_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_PN7150B0HN_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_PN7150B0HN_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_NRF24L01_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_NRF24L01_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_TEMPERATURE_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_TEMPERATURE_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_LASER_DRIVER_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_LASER_DRIVER_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_SAFETY_INTERLOCK_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_SAFETY_INTERLOCK_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_WIRE_FOOTCONTROL_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_WIRE_FOOTCONTROL_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE]; 
extern code char LANG_CHECK_DISPLAY_FIBER_SENSOR_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_FIBER_SENSOR_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_WIRELESS_FOOTCONTROL_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_WIRELESS_FOOTCONTROL_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE]; 
extern code char LANG_CHECK_DISPLAY_PROBATION_PASS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_CHECK_DISPLAY_PROBATION_FAIL[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_WARN_MSG_INTERLOCK_UNPLUG[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_WARN_MSG_FOOTSWITCH_UNPLUG[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_WARN_MSG_ESTOP_PRESS[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_WARN_MSG_FIBER_UNPLUG[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_WARN_MSG_FIBER_MISSMATE[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_WARN_MSG_DIODE0_HTEMP[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_WARN_MSG_DIODE1_HTEMP[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_WARN_MSG_ENVI_HTEMP[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
extern code char LANG_WARN_MSG_DRIVE_HTEMP[DEF_LANG_NUM][DEF_LANG_CHECK_DISPLAY_SIZE];
#endif
