#include "sPlcLaser.h"
/*****************************************************************************/
sbit LASER_980_MODPIN = P2^7;
sbit LASER_1470_MODPIN = P2^6;
#if CONFIG_DEBUG_TIMER4 == 1
bit debugTimer4;
#endif
/*****************************************************************************/
static void initTimer4(void);
/*****************************************************************************/
void testBenchLaserTimer(uint8_t st){//LASER激光发射测试
	EDLAR();
	if(st == 0){//980 CW模式测试
		NVRAM0[SPREG_LASER_MODE] = LASER_MODE_CW;
		NVRAM0[SPREG_LASER_SELECT] = LASER_SELECT_980;
		NVRAM0[SPREG_LASER_TMATE] = 0;//激光脉冲正脉宽 10mS
		NVRAM0[SPREG_LASER_TOVERTIME] = 0;//激光脉冲周期 25mS
		NVRAM0[SPREG_LASER_CURRENT_980] = 200;
		NVRAM0[SPREG_LASER_CURRENT_1470] = 300;
		STLAR();
	}
	if(st == 1){//1470 CW模式测试
		NVRAM0[SPREG_LASER_MODE] = LASER_MODE_CW;
		NVRAM0[SPREG_LASER_SELECT] = LASER_SELECT_1470;
		NVRAM0[SPREG_LASER_TMATE] = 5;//激光脉冲正脉宽 10mS
		NVRAM0[SPREG_LASER_TOVERTIME] = 15;//激光脉冲周期 25mS
		NVRAM0[SPREG_LASER_CURRENT_980] = 300;
		NVRAM0[SPREG_LASER_CURRENT_1470] = 400;
		STLAR();
	}
	if(st == 2){//980+1470 CW模式测试
		NVRAM0[SPREG_LASER_MODE] = LASER_MODE_CW;
		NVRAM0[SPREG_LASER_SELECT] = LASER_SELECT_BOTH;
		NVRAM0[SPREG_LASER_TMATE] = 12;//激光脉冲正脉宽 10mS
		NVRAM0[SPREG_LASER_TOVERTIME] = 21;//激光脉冲周期 25mS
		NVRAM0[SPREG_LASER_CURRENT_980] = 500;
		NVRAM0[SPREG_LASER_CURRENT_1470] = 600;
		STLAR();
	}
	if(st == 3){//980 SP模式测试
		NVRAM0[SPREG_LASER_MODE] = LASER_MODE_SP;
		NVRAM0[SPREG_LASER_SELECT] = LASER_SELECT_980;
		NVRAM0[SPREG_LASER_TMATE] = 50;//激光脉冲正脉宽 10mS
		NVRAM0[SPREG_LASER_TOVERTIME] = 200;//激光脉冲周期 25mS
		NVRAM0[SPREG_LASER_CURRENT_980] = 700;
		NVRAM0[SPREG_LASER_CURRENT_1470] = 800;
		STLAR();
	}
	if(st == 4){//1480 SP模式测试
		NVRAM0[SPREG_LASER_MODE] = LASER_MODE_SP;
		NVRAM0[SPREG_LASER_SELECT] = LASER_SELECT_1470;
		NVRAM0[SPREG_LASER_TMATE] = 25;//激光脉冲正脉宽 10mS
		NVRAM0[SPREG_LASER_TOVERTIME] = 100;//激光脉冲周期 25mS
		NVRAM0[SPREG_LASER_CURRENT_980] = 900;
		NVRAM0[SPREG_LASER_CURRENT_1470] = 1000;
		STLAR();
	}
	if(st == 5){//980+1470 SP模式测试
		NVRAM0[SPREG_LASER_MODE] = LASER_MODE_SP;
		NVRAM0[SPREG_LASER_SELECT] = LASER_SELECT_BOTH;
		NVRAM0[SPREG_LASER_TMATE] = 30;//激光脉冲正脉宽 10mS
		NVRAM0[SPREG_LASER_TOVERTIME] = 90;//激光脉冲周期 25mS
		NVRAM0[SPREG_LASER_CURRENT_980] = 1100;
		NVRAM0[SPREG_LASER_CURRENT_1470] = 1200;
		STLAR();
	}
	if(st == 6){//980 MP模式测试
		NVRAM0[SPREG_LASER_MODE] = LASER_MODE_MP;
		NVRAM0[SPREG_LASER_SELECT] = LASER_SELECT_980;
		NVRAM0[SPREG_LASER_TMATE] = 30;//激光脉冲正脉宽 10mS
		NVRAM0[SPREG_LASER_TOVERTIME] = 90;//激光脉冲周期 25mS
		NVRAM0[SPREG_LASER_CURRENT_980] = 1300;
		NVRAM0[SPREG_LASER_CURRENT_1470] = 1400;
		STLAR();
	}
	if(st == 7){//1470 MP模式测试
		NVRAM0[SPREG_LASER_MODE] = LASER_MODE_MP;
		NVRAM0[SPREG_LASER_SELECT] = LASER_SELECT_1470;
		NVRAM0[SPREG_LASER_TMATE] = 74;//激光脉冲正脉宽 10mS
		NVRAM0[SPREG_LASER_TOVERTIME] = 96;//激光脉冲周期 25mS
		NVRAM0[SPREG_LASER_CURRENT_980] = 1500;
		NVRAM0[SPREG_LASER_CURRENT_1470] = 1600;
		STLAR();
	}
	if(st == 8){//980+1470 MP模式测试
		NVRAM0[SPREG_LASER_MODE] = LASER_MODE_MP;
		NVRAM0[SPREG_LASER_SELECT] = LASER_SELECT_BOTH;
		NVRAM0[SPREG_LASER_TMATE] = 53;//激光脉冲正脉宽 10mS
		NVRAM0[SPREG_LASER_TOVERTIME] = 130;//激光脉冲周期 25mS
		NVRAM0[SPREG_LASER_CURRENT_980] = 1700;
		NVRAM0[SPREG_LASER_CURRENT_1470] = 1800;
		STLAR();
	}
	if(st == 9){//980 GP模式测试
		NVRAM0[SPREG_LASER_MODE] = LASER_MODE_GP;
		NVRAM0[SPREG_LASER_SELECT] = LASER_SELECT_980;
		NVRAM0[SPREG_LASER_TMATE] = 10;//激光脉冲正脉宽 10mS
		NVRAM0[SPREG_LASER_TOVERTIME] = 15;//激光脉冲周期 25mS
		NVRAM0[SPREG_LASER_PMATE] = 10;//10个脉冲
		NVRAM0[SPREG_LASER_POVERTIME] = 33;//间隔33mS
		NVRAM0[SPREG_LASER_CURRENT_980] = 1900;
		NVRAM0[SPREG_LASER_CURRENT_1470] = 2000;
		STLAR();
	}
	if(st == 10){//1470 GP模式测试
		NVRAM0[SPREG_LASER_MODE] = LASER_MODE_GP;
		NVRAM0[SPREG_LASER_SELECT] = LASER_SELECT_1470;
		NVRAM0[SPREG_LASER_TMATE] = 19;//激光脉冲正脉宽 10mS
		NVRAM0[SPREG_LASER_TOVERTIME] = 86;//激光脉冲周期 25mS
		NVRAM0[SPREG_LASER_PMATE] = 12;//10个脉冲
		NVRAM0[SPREG_LASER_POVERTIME] = 43;//间隔33mS
		NVRAM0[SPREG_LASER_CURRENT_980] = 2100;
		NVRAM0[SPREG_LASER_CURRENT_1470] = 2200;
		STLAR();
	}
	if(st == 11){//980+1470 GP模式测试
		NVRAM0[SPREG_LASER_MODE] = LASER_MODE_GP;
		NVRAM0[SPREG_LASER_SELECT] = LASER_SELECT_BOTH;
		NVRAM0[SPREG_LASER_TMATE] = 5;//激光脉冲正脉宽 10mS
		NVRAM0[SPREG_LASER_TOVERTIME] = 24;//激光脉冲周期 25mS
		NVRAM0[SPREG_LASER_PMATE] = 6;//10个脉冲
		NVRAM0[SPREG_LASER_POVERTIME] = 60;//间隔33mS
		NVRAM0[SPREG_LASER_CURRENT_980] = 2300;
		NVRAM0[SPREG_LASER_CURRENT_1470] = 2400;
		STLAR();
	}
}

void STLAR(void) reentrant{//开始发射脉冲
	uint8_t SFRPAGE_save;
	NVRAM0[SPREG_LASER_PCOUNTER] = 0X0;
	NVRAM0[SPREG_LASER_TCOUNTER] = 0X00;	
	SFRPAGE = TMR4_PAGE;
	TMR4CN &= ~(uint8_t)(1 << 7);//TF4 溢出标志清零
	EIE2 |= (1 << 2);//T4 ET3中断使能
	TMR4L = 0xFF;
	TMR4H = 0xFF;
	TMR4CN |= (1 << 2);//TR3 使能TIMER3计时器
	SFRPAGE = SFRPAGE_save;
	SET(SPCOIL_LASER_EMITING);//发射标志置位
	RES(SPCOIL_LASER_EMITOVER);
}
void EDLAR(void) reentrant{//停止发射脉冲
	uint8_t SFRPAGE_save;
	SFRPAGE = TMR4_PAGE;
	TMR4CN &= ~(uint8_t)(1 << 2);//Stop Timer 4
	TMR4CN &= ~(uint8_t)(1 << 7);//Clear Timer 4 High Byte Overflow Flag.
	EIE2 &= ~(uint8_t)(1 << 2);//关闭Timer4中断
	SFRPAGE = SFRPAGE_save;
	//关闭DAC输出
	NVRAM0[SPREG_DAC_0] = 0;
	NVRAM0[SPREG_DAC_1] = 1;
	UPDAC0();
	UPDAC1();
	RES(SPCOIL_LASER_EMITING);//发射标志置位
}
void sPlcLaserInit(void){//激光脉冲功能初始化
	LASER_980_MODPIN = 0;
	LASER_1470_MODPIN = 0;
	initTimer4();
	
}
static void initTimer4(void){//TIMER4初始化
	xdata uint16_t temp;
	xdata uint8_t SFRPAGE_SAVE;
	SFRPAGE_SAVE = SFRPAGE;             // Preserve SFRPAGE
	SFRPAGE = TMR4_PAGE;
	temp = (uint16_t)(65536 - (CONFIG_SYSCLK / 12 / CONFIG_LASER_TIMER_TICK));
	TMR4CF = 0;//	
	RCAP4 = temp;// Reload value to be used in Timer3
	TMR4 = RCAP4;// Init the Timer3 register
	TMR4CN = 0;//16Bit AutoReload
	SFRPAGE = SFRPAGE_SAVE;   
}
void timer4Isr(void) interrupt INTERRUPT_TIMER4{//TIMER4 中断 激光发射
	uint8_t SFRPAGE_save;	
#if CONFIG_DEBUG_TIMER4 == 1
	debugTimer4 = ~debugTimer4;
#endif
	SFRPAGE_save = SFRPAGE;
	SFRPAGE = TMR4_PAGE;
	TMR4CN &= ~(uint8_t)(1 << 7);//Clear Timer 4 High Byte Overflow Flag
	SFRPAGE = SFRPAGE_save;
	switch(NVRAM0[SPREG_LASER_MODE]){
		case LASER_MODE_CW:{//CW连续模式
			if(NVRAM0[SPREG_LASER_SELECT] == LASER_SELECT_980){//980激光通道
				NVRAM0[SPREG_DAC_0] = NVRAM0[SPREG_LASER_CURRENT_980];//电流值写入DAC寄存器
				UPDAC0();//DAC立即输出计时器值
				LASER_980_MODPIN = true;				
			}
			else{
				NVRAM0[SPREG_DAC_0] = 0;//电流值写入DAC寄存器
				UPDAC0();//DAC立即输出计时器值
				LASER_980_MODPIN = false;
			}
			if(NVRAM0[SPREG_LASER_SELECT] == LASER_SELECT_1470){//1470激光通道
				NVRAM0[SPREG_DAC_1] = NVRAM0[SPREG_LASER_CURRENT_1470];//电流值写入DAC寄存器
				UPDAC1();//DAC立即输出计时器值
				LASER_1470_MODPIN = true; 
			}
			else{
				NVRAM0[SPREG_DAC_1] = 0;//电流值写入DAC寄存器
				UPDAC1();//DAC立即输出计时器值
				LASER_1470_MODPIN = false; 
			}
			if(NVRAM0[SPREG_LASER_SELECT] == LASER_SELECT_BOTH){//980+1470激光通道
				NVRAM0[SPREG_DAC_0] = NVRAM0[SPREG_LASER_CURRENT_980];//电流值写入DAC寄存器
				NVRAM0[SPREG_DAC_1] = NVRAM0[SPREG_LASER_CURRENT_1470];//电流值写入DAC寄存器
				UPDAC0();//DAC立即输出计时器值
				UPDAC1();//DAC立即输出计时器值
				LASER_980_MODPIN = true;	
				LASER_1470_MODPIN = false; 				
			}
			break;
		}
		case LASER_MODE_SP:{//SP单脉冲模式
			if(NVRAM0[SPREG_LASER_TCOUNTER] == 0){//翻转
				if(NVRAM0[SPREG_LASER_SELECT] == LASER_SELECT_980){//980激光通道
					NVRAM0[SPREG_DAC_0] = NVRAM0[SPREG_LASER_CURRENT_980];//电流值写入DAC寄存器
					UPDAC0();//DAC立即输出计时器值
					LASER_980_MODPIN = true; 
				}
				else{
					NVRAM0[SPREG_DAC_0] = 0;//电流值写入DAC寄存器
					UPDAC0();//DAC立即输出计时器值
					LASER_980_MODPIN = false;
				}
				if(NVRAM0[SPREG_LASER_SELECT] == LASER_SELECT_1470){//1470激光通道
					NVRAM0[SPREG_DAC_1] = NVRAM0[SPREG_LASER_CURRENT_1470];//电流值写入DAC寄存器
					UPDAC1();//DAC立即输出计时器值
					LASER_1470_MODPIN = true; 
				}
				else{
					NVRAM0[SPREG_DAC_1] = 0;//电流值写入DAC寄存器
					UPDAC1();//DAC立即输出计时器值
					LASER_1470_MODPIN = false; 
				}
				if(NVRAM0[SPREG_LASER_SELECT] == LASER_SELECT_BOTH){//980+1470激光通道
					NVRAM0[SPREG_DAC_0] = NVRAM0[SPREG_LASER_CURRENT_980];//电流值写入DAC寄存器
					NVRAM0[SPREG_DAC_1] = NVRAM0[SPREG_LASER_CURRENT_1470];//电流值写入DAC寄存器
					UPDAC0();//DAC立即输出计时器值
					UPDAC1();//DAC立即输出计时器值
					LASER_980_MODPIN = true;	
					LASER_1470_MODPIN = true; 	
				}
			}
			if(NVRAM0[SPREG_LASER_TCOUNTER] >= NVRAM0[SPREG_LASER_TMATE]){//计时器匹配
				NVRAM0[SPREG_DAC_0] = 0x0;//电流值写入DAC寄存器
				UPDAC0();//DAC立即输出计时器值
				NVRAM0[SPREG_DAC_1] = 0x0;//电流值写入DAC寄存器
				UPDAC1();//DAC立即输出计时器值
				LASER_980_MODPIN = false;
				LASER_1470_MODPIN = false;//翻转输出
				SET(SPCOIL_LASER_EMITOVER);
				EDLAR();//停止脉冲发射
			}
			NVRAM0[SPREG_LASER_TCOUNTER] ++;
			break;
		}
		case LASER_MODE_MP:{//MP多脉冲模式	
			if(NVRAM0[SPREG_LASER_TCOUNTER] == 0){//翻转	
				if(NVRAM0[SPREG_LASER_SELECT] == LASER_SELECT_980){//980激光通道
					NVRAM0[SPREG_DAC_0] = NVRAM0[SPREG_LASER_CURRENT_980];//电流值写入DAC寄存器
					UPDAC0();//DAC立即输出计时器值
					LASER_980_MODPIN = true; 
				}
				else{
					NVRAM0[SPREG_DAC_0] = 0;//电流值写入DAC寄存器
					UPDAC0();//DAC立即输出计时器值
					LASER_980_MODPIN = false;
				}
				if(NVRAM0[SPREG_LASER_SELECT] == LASER_SELECT_1470){//1470激光通道
					NVRAM0[SPREG_DAC_1] = NVRAM0[SPREG_LASER_CURRENT_1470];//电流值写入DAC寄存器
					UPDAC1();//DAC立即输出计时器值
					LASER_1470_MODPIN = true; 
				}
				else{
					NVRAM0[SPREG_DAC_1] = 0;//电流值写入DAC寄存器
					UPDAC1();//DAC立即输出计时器值
					LASER_1470_MODPIN = false; 
				}
				if(NVRAM0[SPREG_LASER_SELECT] == LASER_SELECT_BOTH){
					NVRAM0[SPREG_DAC_0] = NVRAM0[SPREG_LASER_CURRENT_980];//电流值写入DAC寄存器
					NVRAM0[SPREG_DAC_1] = NVRAM0[SPREG_LASER_CURRENT_1470];//电流值写入DAC寄存器
					UPDAC0();//DAC立即输出计时器值
					UPDAC1();//DAC立即输出计时器值
					LASER_980_MODPIN = true; 
					LASER_1470_MODPIN = true; 
				}
			}
			if(NVRAM0[SPREG_LASER_TCOUNTER] == NVRAM0[SPREG_LASER_TMATE]){//计时器匹配
				NVRAM0[SPREG_DAC_0] = 0x0;//电流值写入DAC寄存器
				UPDAC0();//DAC立即输出计时器值
				NVRAM0[SPREG_DAC_1] = 0x0;//电流值写入DAC寄存器
				UPDAC1();//DAC立即输出计时器值
				LASER_980_MODPIN = false;
				LASER_1470_MODPIN = false;//翻转输出		
			}
			if(NVRAM0[SPREG_LASER_TCOUNTER] >= NVRAM0[SPREG_LASER_TOVERTIME]){//计时器溢出
				NVRAM0[SPREG_LASER_TCOUNTER] = -1;//清零
			}
			NVRAM0[SPREG_LASER_TCOUNTER] ++;
			break;
		}
		case LASER_MODE_GP:{//GP可编程脉冲模式
			if(NVRAM0[SPREG_LASER_PCOUNTER] < NVRAM0[SPREG_LASER_PMATE]){//脉冲串输出
				if(NVRAM0[SPREG_LASER_TCOUNTER] == 0){//翻转	
					if(NVRAM0[SPREG_LASER_SELECT] == LASER_SELECT_980){//980激光通道
						NVRAM0[SPREG_DAC_0] = NVRAM0[SPREG_LASER_CURRENT_980];//电流值写入DAC寄存器
						UPDAC0();//DAC立即输出计时器值
						LASER_980_MODPIN = true; 
					}
					else{
						NVRAM0[SPREG_DAC_0] = 0;//电流值写入DAC寄存器
						UPDAC0();//DAC立即输出计时器值
						LASER_980_MODPIN = false;
					}
					if(NVRAM0[SPREG_LASER_SELECT] == LASER_SELECT_1470){//1470激光通道
						NVRAM0[SPREG_DAC_1] = NVRAM0[SPREG_LASER_CURRENT_1470];//电流值写入DAC寄存器
						UPDAC1();//DAC立即输出计时器值
						LASER_1470_MODPIN = true; 
					}
					else{
						NVRAM0[SPREG_DAC_1] = 0;//电流值写入DAC寄存器
						UPDAC1();//DAC立即输出计时器值
						LASER_1470_MODPIN = false; 
					}
					if(NVRAM0[SPREG_LASER_SELECT] == LASER_SELECT_BOTH){//1470激光通道
						NVRAM0[SPREG_DAC_0] = NVRAM0[SPREG_LASER_CURRENT_980];//电流值写入DAC寄存器
						NVRAM0[SPREG_DAC_1] = NVRAM0[SPREG_LASER_CURRENT_1470];//电流值写入DAC寄存器
						UPDAC0();//DAC立即输出计时器值
						UPDAC1();//DAC立即输出计时器值
						LASER_980_MODPIN = true;
						LASER_1470_MODPIN = true; 
					}
				}
				if(NVRAM0[SPREG_LASER_TCOUNTER] == NVRAM0[SPREG_LASER_TMATE]){//计时器匹配
					NVRAM0[SPREG_DAC_0] = 0x0;//电流值写入DAC寄存器
					UPDAC0();//DAC立即输出计时器值
					NVRAM0[SPREG_DAC_1] = 0x0;//电流值写入DAC寄存器
					UPDAC1();//DAC立即输出计时器值
					LASER_980_MODPIN = false;
					LASER_1470_MODPIN = false;//翻转输出		
				}
				if(NVRAM0[SPREG_LASER_TCOUNTER] >= NVRAM0[SPREG_LASER_TOVERTIME]){//计时器溢出
					NVRAM0[SPREG_LASER_TCOUNTER] = -1;//清零
					NVRAM0[SPREG_LASER_PCOUNTER] ++;
				}
				NVRAM0[SPREG_LASER_TCOUNTER] ++;
			}
			if(NVRAM0[SPREG_LASER_PCOUNTER] >= NVRAM0[SPREG_LASER_PMATE]){//多脉冲间隔		
				if(NVRAM0[SPREG_LASER_PCOUNTER] >= (NVRAM0[SPREG_LASER_POVERTIME] + NVRAM0[SPREG_LASER_PMATE])){//脉冲个数发现匹配
					NVRAM0[SPREG_LASER_PCOUNTER] = -1;
					NVRAM0[SPREG_LASER_TCOUNTER] = 0;
				}
				NVRAM0[SPREG_LASER_PCOUNTER] ++;
			}
			break;
		}
		default:break;
	}
}
